version: "3.7"

services:
  nginx:
    build: ./nginx
    ports:
      - "1300:8000"
    volumes:
      - static_volume:/test_task/static
    depends_on:
      - db
      - web
    restart: "on-failure"
  web:
    build: .
    command: python manage.py makemigrations && python manage.py migrate && python manage.py loaddata testdata.json && python manage.py collectstatic --noinput && python server.py
    volumes:
      - .:/test_task
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: "on-failure"
  db:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgis_31
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    command: -p 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"
volumes:
  postgres_data:
  static_volume: